// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzm5T4I7IrOhf4dU8BnrVKtfVyq-oavik',
    appId: '1:1099347607119:web:7a315efac39f6deab6743a',
    messagingSenderId: '1099347607119',
    projectId: 'parcial2sw1',
    authDomain: 'parcial2sw1.firebaseapp.com',
    storageBucket: 'parcial2sw1.appspot.com',
    measurementId: 'G-XK0GTQLF7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMZTUszHC8w1VvjTysx64LVr6byT9J2Rc',
    appId: '1:1099347607119:android:9f49bb58a757fc13b6743a',
    messagingSenderId: '1099347607119',
    projectId: 'parcial2sw1',
    storageBucket: 'parcial2sw1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtrcS6HQ_h50ye5OIrRsuPxJ7i-UHky-8',
    appId: '1:1099347607119:ios:16b5ce0286c58c84b6743a',
    messagingSenderId: '1099347607119',
    projectId: 'parcial2sw1',
    storageBucket: 'parcial2sw1.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtrcS6HQ_h50ye5OIrRsuPxJ7i-UHky-8',
    appId: '1:1099347607119:ios:16b5ce0286c58c84b6743a',
    messagingSenderId: '1099347607119',
    projectId: 'parcial2sw1',
    storageBucket: 'parcial2sw1.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzm5T4I7IrOhf4dU8BnrVKtfVyq-oavik',
    appId: '1:1099347607119:web:a0b9c262f271d1abb6743a',
    messagingSenderId: '1099347607119',
    projectId: 'parcial2sw1',
    authDomain: 'parcial2sw1.firebaseapp.com',
    storageBucket: 'parcial2sw1.appspot.com',
    measurementId: 'G-P5LN3M3HF3',
  );
}
